#!/usr/bin/env python

#                  High-Level Reduction Functions
#           A part of the SNS Analysis Software Suite.
#
#                  Spallation Neutron Source
#          Oak Ridge National Laboratory, Oak Ridge TN.
#
#
#                             NOTICE
#
# For this software and its associated documentation, permission is granted
# to reproduce, prepare derivative works, and distribute copies to the public
# for any purpose and without fee.
#
# This material was prepared as an account of work sponsored by an agency of
# the United States Government.  Neither the United States Government nor the
# United States Department of Energy, nor any of their employees, makes any
# warranty, express or implied, or assumes any legal liability or
# responsibility for the accuracy, completeness, or usefulness of any
# information, apparatus, product, or process disclosed, or represents that
# its use would not infringe privately owned rights.
#

# $Id$

"""
This program covers the functionality outlined in 2.2.1 Powder or
amorphous material reduction in
http://www.sns.gov/asg/projects/SCL/reqspec/DR_Lib_RS.doc
"""

def run(config, tim=None):
    import DST

    if tim is not None:
        tim.getTime(False)
        old_time = tim.getOldTime()

    if config.data is None:
        raise RuntimeError("Need to pass a data filename to the driver "\
                           +"script.")

    # Read in geometry if one is provided
    if config.inst_geom is not None:
        if config.verbose:
            print "Reading in instrument geometry file"
            
        inst_geom_dst = DST.getInstance("application/x-NxsGeom",
                                        config.inst_geom)
    else:
        inst_geom_dst = None

    # Perform Steps 1-9 on sample data
    d_som1 = dr_lib.process_igs_data(config.data, config, timer=tim,
                                     inst_geom_dst=inst_geom_dst,
                                     tib_const=config.tib_data_const)

    # Perform Steps 1-9 on empty can data
    if config.ecan is not None:
        e_som1 = dr_lib.process_igs_data(config.ecan, config, timer=tim,
                                         inst_geom_dst=inst_geom_dst,
                                         dataset_type="empty_can",
                                         tib_const=config.tib_ecan_const)
    else:
        e_som1 = None

    # Perform Steps 1-9 on normalization data            
    if config.norm is not None:
        n_som1 = dr_lib.process_igs_data(config.norm, config, timer=tim,
                                         inst_geom_dst=inst_geom_dst,
                                         dataset_type="normalization",
                                         tib_const=config.tib_norm_const)
    else:
        n_som1 = None

    # Perform Steps 1-9 on background data
    if config.back is not None:
        b_som1 = dr_lib.process_igs_data(config.back, config, timer=tim,
                                         inst_geom_dst=inst_geom_dst,
                                         dataset_type="background",
                                         tib_const=config.tib_back_const)
    else:
        b_som1 = None

    if inst_geom_dst is not None:
        inst_geom_dst.release_resource()
        
    # Step 10: Subtract background spectrum from sample spectrum    
    d_som2 = dr_lib.subtract_bkg_from_data(d_som1, b_som1,
                                           verbose=config.verbose,
                                           timer=tim,
                                           dataset1="data",
                                           dataset2="background")

    # Step 11: Subtract background spectrum from empty can spectrum    
    e_som2 = dr_lib.subtract_bkg_from_data(e_som1, b_som1,
                                           verbose=config.verbose,
                                           timer=tim,
                                           dataset1="empty_can",
                                           dataset2="background")

    # Step 12: Subtract background spectrum from normalization spectrum
    n_som2 = dr_lib.subtract_bkg_from_data(n_som1, b_som1,
                                           verbose=config.verbose,
                                           timer=tim,
                                           dataset1="normalization",
                                           dataset2="background")
    del b_som1

    # Step 13: Subtract empty can spectrum from sample spectrum    
    d_som3 = dr_lib.subtract_bkg_from_data(d_som2, e_som2,
                                           verbose=config.verbose,
                                           timer=tim,
                                           dataset1="data",
                                           dataset2="empty_can")

    del d_som2
    
    # Step 14: Subtract empty can spectrum from normalization spectrum
    n_som3 = dr_lib.subtract_bkg_from_data(n_som2, e_som2,
                                           verbose=config.verbose,
                                           timer=tim,
                                           dataset1="normalization",
                                           dataset2="empty_can")    

    del n_som2, e_som2

    # Step 15: Integrate normalization spectra
    if config.verbose and n_som3 is not None:
        print "Integrating normalization spectra"

    norm_int = dr_lib.integrate_spectra(n_som3, start=config.norm_start,
                                        end=config.norm_end)

    del n_som3
        
    # Step 16: Normalize data by integrated values
    if config.verbose and norm_int is not None:
        print "Normalizing data by normalization data"

    if norm_int is not None:
        d_som4 = common_lib.div_ncerr(d_som3, norm_int)
    else:
        d_som4 = d_som3

    if norm_int is not None:
        if tim is not None:
            tim.getTime(msg="After normalizing data ")

    del d_som3, norm_int

    # Step 17: Convert initial wavelength to E_initial
    if config.verbose:
        print "Converting initial wavelength to E_initial"

    if tim is not None:
        tim.getTime(False)

    d_som6 = common_lib.wavelength_to_energy(d_som4)

    if tim is not None:
        tim.getTime(msg="After converting initial wavelength to E_initial ")

    if config.dump_initial_energy:
        hlr_utils.write_file(config.data[0], "text/Spec", d_som6,
                             output_ext="ixl",
                             verbose=config.verbose,
                             message="pixel initial energy information")

    del d_som4

    # Steps 19-20: Calculate energy transfer
    if config.verbose:
        print "Calculating energy transfer"

    if tim is not None:
        tim.getTime(False)

    d_som7 = dr_lib.igs_energy_transfer(d_som6)

    if tim is not None:
        tim.getTime(msg="After calculating energy transfer ")

    if config.dump_energy:
        hlr_utils.write_file(config.data[0], "text/Spec", d_som7,
                             output_ext="exl",
                             verbose=config.verbose,
                             message="pixel energy transfer information")

    # Write 3-column ASCII file for E_t
    d_som7_1 = dr_lib.sum_all_spectra(d_som7, rebin_axis=config.E_bins)
    hlr_utils.write_file(config.data[0], "text/Spec", d_som7_1,
                         output_ext="etr",
                         verbose=config.verbose,
                         message="combined energy transfer information") 
    
    del d_som7_1

    # Steps 18-20: Calculate scaled energy transfer
    if config.verbose:
        print "Calculating scaled energy transfer"

    d_som9 = dr_lib.igs_energy_transfer(d_som6, scale=True)

    if tim is not None:
        tim.getTime(msg="After calculating scaled energy transfer ")

    if config.dump_energy:
        hlr_utils.write_file(config.data[0], "text/Spec", d_som9,
                             output_ext="sexl",
                             verbose=config.verbose,
                             message="pixel scaled energy transfer "\
                             +"information")

    # Write 3-column ASCII file for scaled E_t
    d_som9_1 = dr_lib.sum_all_spectra(d_som9, rebin_axis=config.E_bins)
    hlr_utils.write_file(config.data[0], "text/Spec", d_som9_1,
                         output_ext="setr",
                         verbose=config.verbose,
                         message="combined scaled energy transfer "\
                         +"information") 
    
    del d_som9_1

    del d_som6, d_som7

    # Steps 21-25: Calculate Q and create S(Q, E_t)
    if config.verbose:
        print "Creating 2D spectrum"

    if tim is not None:
        tim.getTime(False)

    if config.correct:
        d_som8 = dr_lib.create_E_vs_Q_igs(d_som9,
                                          config.E_bins, config.Q_bins,
                                          so_id="Full Detector",
                                          y_label="counts",
                                          y_units="counts / (ueV * A^-1)",
                                          x_labels=["Q transfer",
                                                    "energy transfer"],
                                          x_units=["1/Angstroms","ueV"])
    else:
        d_som8 = dr_lib.create_2D_dist(d_som9, config.E_bins, config.Q_bins,
                                       so_id="Full Detector",
                                       y_label="counts",
                                       y_units="counts / (ueV * A^-1)",
                                       x_labels=["Q transfer",
                                                 "energy transfer"],
                                       x_units=["1/Angstroms","ueV"])

    if tim is not None:
        tim.getTime(msg="After creation of final spectrum ")

    del d_som9

    # Writing 2D DAVE file

    hlr_utils.write_file(config.output, "text/Dave2d", d_som8,
                         verbose=config.verbose,
                         message="data",
                         replace_path=False,
                         replace_ext=False)

    d_som8.attr_list["config"] = config

    hlr_utils.write_file(config.data[0], "text/rmd", d_som8,
                         output_ext="rmd",
                         verbose=config.verbose,
                         message="metadata")
    
    if tim is not None:
        tim.setOldTime(old_time)
        tim.getTime(msg="Total Running Time: ")

if __name__ == "__main__":
    import common_lib
    import dr_lib
    import hlr_utils

    # Make description for driver
    result = []
    result.append("This driver runs the data reduction for the inelastic")
    result.append("banks for the BSS instrument. The standard output is a")
    result.append("*.txt file (DAVE Grouped ASCII) for S(Q,E), a *.setr file")
    result.append("(3-column ASCII) for S(E) and a *.etr file (3-column")
    result.append("ASCII) for sigma(E). Other intermediate files can be")
    result.append("produced by using the appropriate dump-X flag described in")
    result.append("this help. The file extensions are described in the option")
    result.append("documentation.")
 
    # Set up the options available
    parser = hlr_utils.IgsOptions("usage: %prog [options] <datafile>", None,
                                  hlr_utils.program_version(), 'error',
                                  " ".join(result))

    # Set defaults for imported options
    parser.set_defaults(inst="BSS")
    parser.set_defaults(data_paths="/entry/bank1,1,/entry/bank2,1")
    parser.set_defaults(mon_path="/entry/monitor,1")
    parser.set_defaults(norm_start="6.24")
    parser.set_defaults(norm_end="6.30")
    
    # Add amorphous_reduction specific options
    parser.add_option("", "--mon-eff", dest="mon_eff", metavar="TUPLE",
                      help="Specify the monitor efficiency file or an "\
                      +"efficiency tuple (efficiency,error2)")
    
    parser.add_option("", "--det-eff", dest="det_eff",
                      help="Specify the detector efficiency file or an "\
                      +"efficiency tuple (efficiency,error2)")
    
    parser.add_option("", "--energy-bins", dest="E_bins",
                      help="Specify the minimum and maximum energy values and"\
                      +" the energy bin width in ueV")
    
    parser.add_option("", "--mom-trans-bins", dest="Q_bins",
                      help="Specify the minimum and maximum momentum transfer"\
                      +" values and the momentum transfer bin width in"\
                      +" Angstroms^-1")
    
    parser.add_option("", "--dump-energy", action="store_true",
                      dest="dump_energy",
                      help="Flag to dump the energy transfer information for"\
                      +" all pixels. Creates a *.exl file.")
    parser.set_defaults(dump_energy=False)
    
    parser.add_option("", "--dump-ei", action="store_true",
                      dest="dump_initial_energy",
                      help="Flag to dump the initial energy information for"\
                      +" all pixels. Creates a *.ixl file.")
    parser.set_defaults(dump_ei=False)
    
    parser.add_option("", "--correct", action="store_true", dest="correct",
                      help="Flag to turn on correct calculation of Q")
    parser.set_defaults(correct=False)

    parser.add_option("", "--timing", action="store_true", dest="timing",
                      help="Flag to turn on timing of code")
    parser.set_defaults(timing=False)
    
    (options, args) = parser.parse_args()

    # Set up the configuration
    configure = hlr_utils.Configure()

    # Call the configuration setter for IgsOptions
    hlr_utils.IgsConfiguration(parser, configure, options, args)

    # Set the monitor efficiency (tuple)
    configure.mon_eff = hlr_utils.split_values(options.mon_eff)

    # Set the detector efficiency. This can be a tuple (one number for all
    # pixels) or a file containing numbers for all pixels.
    try:
        configure.det_eff = hlr_utils.split_values(options.det_eff)
    except ValueError:
        configure.det_eff = hlr_utils.determine_files(options.det_eff,
                                                      one_file=True)
            
    # Set the E bins
    if options.E_bins is not None:
        efacts = options.E_bins.split(',')
        configure.E_bins = hlr_utils.make_axis(float(efacts[0]),
                                               float(efacts[1]),
                                               float(efacts[2]))
    else:
        parser.error("You must provide energy transfer binning via the "\
                     +"energy-bins option")        

    # Set the Q bins
    if options.Q_bins is not None:
        qfacts = options.Q_bins.split(',')
        configure.Q_bins = hlr_utils.make_axis(float(qfacts[0]),
                                               float(qfacts[1]),
                                               float(qfacts[2]))
    else:
        parser.error("You must provide Q binning via the mom-trans-bins "\
                     +"option")

    # Set the ability to dump the energy transfer information
    configure.dump_energy = options.dump_energy
    
    # Set the ability to dump the initial energy information
    configure.dump_initial_energy = options.dump_initial_energy

    if options.dump_all:
        configure.dump_energy = True
        configure.dump_initial_energy = True

    # Set Correct Q calculation flag
    configure.correct = options.correct

    # Set timer object if timing option is used
    if options.timing:
        import sns_timing
        timer = sns_timing.DiffTime()
    else:
        timer = None
    
    # Run the program
    run(configure, timer)
