#!/usr/bin/env python

#                  High-Level Reduction Functions
#           A part of the SNS Analysis Software Suite.
#
#                  Spallation Neutron Source
#          Oak Ridge National Laboratory, Oak Ridge TN.
#
#
#                             NOTICE
#
# For this software and its associated documentation, permission is granted
# to reproduce, prepare derivative works, and distribute copies to the public
# for any purpose and without fee.
#
# This material was prepared as an account of work sponsored by an agency of
# the United States Government.  Neither the United States Government nor the
# United States Department of Energy, nor any of their employees, makes any
# warranty, express or implied, or assumes any legal liability or
# responsibility for the accuracy, completeness, or usefulness of any
# information, apparatus, product, or process disclosed, or represents that
# its use would not infringe privately owned rights.
#

# $Id$

"""
This program covers the functionality outlined in 2.2.2 Calibration of
Energy Transfer=0 Position in <CHANGE:DR_Lib_RS.doc>.
"""

def step1():
    """Step 1. Determine vPeak0 and sign of vPeak0 from S(omega)."""
    pass

def step2():
    """Step 2. Determine L0 and L1 shifts (deltaL0 and deltaL1)."""
    pass

def step3():
    """Step 3. Run reduction from section 2.2.1 beginning at Step 8."""
    pass

def step4():
    """Step 4. Redo Step 1 with corrected scattering function S(v)."""
    pass

def step5():
    """Step 5. Repeat until vPeak0 is within specified tolerance
    (TOL) of zero."""
    pass

if __name__ == "__main__":
    pass
