#!/bin/sh

###############################################################################
#
# Script to generate the API documentation for HLRedux
#
# $Id$
#
###############################################################################
export PYTHONPATH=../build/lib
epydoc --config=config.epy --css=material/epydoc.css

