#!/usr/bin/env python

#                  High-Level Reduction Functions
#           A part of the SNS Analysis Software Suite.
#
#                  Spallation Neutron Source
#          Oak Ridge National Laboratory, Oak Ridge TN.
#
#
#                             NOTICE
#
# For this software and its associated documentation, permission is granted
# to reproduce, prepare derivative works, and distribute copies to the public
# for any purpose and without fee.
#
# This material was prepared as an account of work sponsored by an agency of
# the United States Government.  Neither the United States Government nor the
# United States Department of Energy, nor any of their employees, makes any
# warranty, express or implied, or assumes any legal liability or
# responsibility for the accuracy, completeness, or usefulness of any
# information, apparatus, product, or process disclosed, or represents that
# its use would not infringe privately owned rights.
#

# $Id$

"""
This program covers the functionality outlined in 2.4 Area detector
measurement of specular reflectivity in <CHANGE:DR_Lib_RS.doc>.
"""

def determine_background(conf, bkg_som, btype="sample"):

    if conf.no_bkg and btype == "sample":
        return None
    elif conf.no_norm_bkg and btype == "norm":
        return None    
    else:
        bkg_som1 = dr_lib.sum_all_spectra(bkg_som)
        ratio = (1.0 / float(len(bkg_som)), 0.0)
        return common_lib.mult_ncerr(bkg_som1, ratio)

def run(config, tim):
    import DST
    
    if config.data is None:
        raise RuntimeError("Need to pass a data filename to the driver "\
                           +"script.")
    if tim is not None:
        old_time = tim.getOldTime()

    so_axis = "time_of_flight"

    if config.verbose:
        print "Reading data file"

    (d_som1, b_som1) = dr_lib.add_files(config.data,
                                        Data_Paths=config.data_paths,
                                        SO_Axis=so_axis,
                                        Signal_ROI=config.signal_roi_file,
                                        Bkg_ROI=config.bkg_roi_file,
                                        Verbose=config.verbose,
                                        Timer=tim)

    if tim is not None:
        tim.getTime(msg="After reading data")

    if config.dump_specular:
        d_som1_1 = dr_lib.sum_all_spectra(d_som1)
        hlr_utils.write_file(config.output, "text/Spec", d_som1_1,
                             output_ext="sdc", verbose=config.verbose,
                             data_ext=config.ext_replacement,
                             path_replacement=config.path_replacement,
                             message="combined specular TOF information")
        del d_som1_1

    if config.verbose and not config.no_bkg:
        print "Determining background"

    B = determine_background(config, b_som1)

    if tim is not None:
        tim.getTime(msg="After background determination")

    if not config.no_bkg and config.dump_bkg:
        hlr_utils.write_file(config.output, "text/Spec", B,
                             output_ext="bkg", verbose=config.verbose,
                             data_ext=config.ext_replacement,
                             path_replacement=config.path_replacement,
                             message="combined background TOF information")

    del b_som1

    if not config.no_bkg:
        d_som2 = dr_lib.subtract_bkg_from_data(d_som1, B[0],
                                               verbose=config.verbose,
                                               timer=tim,
                                               dataset1="data",
                                               dataset2="background")
    else:
        d_som2 = d_som1

    del d_som1

    if config.inst_geom is not None:
        if config.verbose:
            print "Reading in detector geometry file"

        inst_geom_dst = DST.getInstance("application/x-NxsGeom",
                                       config.inst_geom)
        inst_geom_dst.setGeometry(config.data_paths, d_som2)
        inst_geom_dst.release_resource()
        
    if config.verbose:
        print "Converting TOF to wavelength"

    d_som3 = common_lib.tof_to_wavelength(d_som2, inst_param="total",
                                          units="microsecond")

    del d_som2
    
    if config.norm is not None:
        if config.verbose:
            print "Reading normalization file"

        if tim is not None:
            tim.getTime(False)

        (nd_som1, nb_som1) = dr_lib.add_files(config.norm,
                                        Data_Paths=config.data_paths,
                                        SO_Axis=so_axis,
                                        Signal_ROI=config.norm_signal_roi_file,
                                        Bkg_ROI=config.norm_bkg_roi_file,
                                        dataset_type="norm",      
                                        Verbose=config.verbose,
                                        Timer=tim)
        
        if tim is not None:
            tim.getTime(msg="After reading normalization file")
    else:
        nd_som1 = None
        nb_som1 = None

    if config.verbose and config.norm is not None:
        print "Scale normalization spectra"

    if config.dump_norm and nd_som1 is not None:
        nd_som1_1 = dr_lib.sum_all_spectra(nd_som1)
        hlr_utils.write_file(config.output, "text/Spec", nd_som1_1,
                             output_ext="nom", verbose=config.verbose,
                             data_ext=config.ext_replacement,
                             path_replacement=config.path_replacement,
                             message="combined normalization TOF information")
        del nd_som1_1

    if config.verbose and not config.no_norm_bkg and config.norm is not None:
        print "Determining normalization background"

    if tim is not None:
        tim.getTime(False)

    if config.norm is not None:
        B_n = determine_background(config, nb_som1, "norm")
    else:
        B_n = None

    del nb_som1

    if tim is not None and not config.no_norm_bkg and config.norm is not None:
        tim.getTime(msg="After normalization background determination")

    if not config.no_norm_bkg and B_n is not None and config.dump_norm_bkg:
        hlr_utils.write_file(config.output, "text/Spec", B_n,
                             output_ext="bnm", verbose=config.verbose,
                             data_ext=config.ext_replacement,
                             path_replacement=config.path_replacement,
                             message="combined normalization background TOF "\
                             +"information")

    if config.norm is not None:
        if not config.no_norm_bkg:
            nd_som2 = dr_lib.subtract_bkg_from_data(nd_som1, B_n[0],
                                                    verbose=config.verbose,
                                                    timer=tim,
                                                    dataset1="normalization",
                                                    dataset2="background")
        else:
            nd_som2 = nd_som1
    else:
        nd_som2 = None
        
    del nd_som1

    if config.verbose and config.norm is not None:
        print "Converting TOF to wavelength (norm)"

    if config.inst_geom is not None:
        if config.verbose:
            print "Reading in detector geometry file"

        inst_geom_dst = DST.getInstance("application/x-NxsGeom",
                                       config.inst_geom)
        inst_geom_dst.setGeometry(config.data_paths, nd_som2)
        inst_geom_dst.release_resource()

    if tim is not None:
        tim.getTime(False)

    if config.norm is not None:
        nd_som3 = common_lib.tof_to_wavelength(nd_som2, inst_param="total",
                                               units="microsecond")
    else:
        nd_som3 = None

    if tim is not None:
        tim.getTime(msg="After wavelength conversion")

    del nd_som2

    if config.verbose:
        print "Combining spectra"

    d_som4 = dr_lib.sum_all_spectra(d_som3, rebin_axis=config.l_bins)
    if config.norm is not None:
        nd_som4 = dr_lib.sum_all_spectra(nd_som3, rebin_axis=config.l_bins)
    else:
        nd_som4 = None

    del d_som3, nd_som3

    if config.verbose and config.norm is not None:
        print "Scale data by normalization"

    if config.norm is not None:
        d_som5 = common_lib.div_ncerr(d_som4, nd_som4)
    else:
        d_som5 = d_som4

    if tim is not None and config.norm is not None:
        tim.getTime(msg="After normalizing signal spectra")

    del d_som4, nd_som4

    if config.det_angle is None:
        d_som5.attr_list["detector_angle"] = (0.0, "degree")
    else:
        d_som5.attr_list["detector_angle"] = config.det_angle

    hlr_utils.write_file(config.output, "text/Spec", d_som5, replace_ext=False,
                         replace_path=False,
                         verbose=config.verbose,
                         message="combined Reflectivity information")

    d_som5.attr_list["config"] = config

    hlr_utils.write_file(config.output, "text/rmd", d_som5,
                         output_ext="rmd", verbose=config.verbose,
                         data_ext=config.ext_replacement,
                         path_replacement=config.path_replacement,
                         message="metadata")

    if tim is not None:
        tim.setOldTime(old_time)
        tim.getTime(msg="Completing driver")

if __name__ == "__main__":
    import os
    
    import common_lib
    import dr_lib
    import hlr_utils
    
    # set up the options available
    parser = hlr_utils.SNSOptions("usage: %prog [options] <datafile>", None,
                                  None, hlr_utils.program_version(),
                                  inst="REF")

    # Defaults for REF
    parser.set_defaults(inst="REF_M")
    parser.set_defaults(data_paths="/entry/bank1,1")

    # Add REF specific options
    parser.add_option("", "--det-angle", dest="det_angle",
                      help="Specify the detector inclination angle, err^2, "\
                      +"and units")

    parser.add_option("", "--l-bins", dest="l_bins",
                      help="Specify the minimum and maximum wavelength values"\
                      +"and the wavelength bin width in Angstroms")

    parser.add_option("", "--dump-specular", action="store_true",
                      dest="dump_specular",
                      help="Flag to dump the combined specular TOF "\
                      +"information")
    parser.set_defaults(dump_specular=False)

    parser.add_option("", "--dump-norm", action="store_true",
                      dest="dump_norm",
                      help="Flag to dump the combined normalization TOF "\
                      +"information")
    parser.set_defaults(dump_norm=False)

    parser.add_option("", "--dump-all", action="store_true", dest="dump_all",
                      help="Flag to dump combined information")
    parser.set_defaults(dump_all=False)

    parser.add_option("", "--no-bkg", action="store_true", dest="no_bkg",
                      help="Flag to turn off background estimation and "\
                      +"subtraction")
    parser.set_defaults(no_bkg=False)

    parser.add_option("", "--dump-bkg", action="store_true", dest="dump_bkg",
                      help="Flag to dump the combined background TOF "\
                      +"information")
    parser.set_defaults(dump_bkg=False)

    parser.add_option("", "--signal-roi-file", dest="signal_roi_file",
                      help="Specify the file containing the list pixel IDs "
                      +"for the signal region.")

    parser.add_option("", "--bkg-roi-file", dest="bkg_roi_file",
                      help="Specify the file containing the list pixel IDs "
                      +"for the background region.")

    parser.add_option("", "--norm-signal-roi-file",
                      dest="norm_signal_roi_file",
                      help="Specify the file containing the list pixel IDs "
                      +"for the normalization signal region.")

    parser.add_option("", "--norm-bkg-roi-file", dest="norm_bkg_roi_file",
                      help="Specify the file containing the list pixel IDs "
                      +"for the normalization background region.")    

    parser.add_option("", "--no-norm-bkg", action="store_true",
                      dest="no_norm_bkg",
                      help="Flag to turn off normalization background "\
                      +"estimation and subtraction")
    parser.set_defaults(no_norm_bkg=False)

    parser.add_option("", "--dump-norm-bkg", action="store_true",
                      dest="dump_norm_bkg",
                      help="Flag to dump the combined normalization "\
                      +"background TOF information")
    parser.set_defaults(dump_norm_bkg=False)

    parser.add_option("", "--timing", action="store_true", dest="timing",
                      help="Flag to turn on timing of code")
    parser.set_defaults(timing=False)

    (options, args) = parser.parse_args()
    
    # set up the configuration
    configure = hlr_utils.Configure()

    # Call the configuration setter for SNSOptions
    hlr_utils.SnsConfiguration(parser, configure, options, args)
    
    # get the data path for the signal ROI file
    configure.signal_roi_file = hlr_utils.determine_files(\
       options.signal_roi_file,
       one_file=True)
    
    # get the data path for the background ROI file
    configure.bkg_roi_file = hlr_utils.determine_files(\
       options.bkg_roi_file,
       one_file=True)
    
    # get the data path for the normalization signal ROI file
    if options.norm_signal_roi_file is not None:
        configure.norm_signal_roi_file = hlr_utils.determine_files(\
       options.norm_signal_roi_file,
       one_file=True)
    else:
        configure.norm_signal_roi_file = configure.signal_roi_file
    
    # get the data path for the normalization background ROI file
    if options.norm_bkg_roi_file is not None:
        configure.norm_bkg_roi_file = hlr_utils.determine_files(\
       options.norm_bkg_roi_file,
       one_file=True)
    else:
        configure.norm_bkg_roi_file = configure.bkg_roi_file

    if options.det_angle is not None:
        configure.det_angle = hlr_utils.split_values(options.det_angle)
    else:
        configure.det_angle = options.det_angle

    # set the wavelength bins
    if options.l_bins is not None:
        lfacts = options.l_bins.split(',')
        configure.l_bins = hlr_utils.make_axis(float(lfacts[0]),
                                               float(lfacts[1]),
                                               float(lfacts[2]))
    else:
        configure.l_bins = options.l_bins

    # set the ability to turn off background estimation and subtraction
    configure.no_bkg = options.no_bkg
    if configure.bkg_roi_file is None and not configure.no_bkg:
        print "Shutting off background subtraction"
        configure.no_bkg = True

    # set the ability to turn off normalization background estimation
    # and subtraction
    configure.no_norm_bkg = options.no_norm_bkg
    if configure.norm_bkg_roi_file is None and not configure.no_norm_bkg:
        configure.no_norm_bkg = True
            
    # set the ability to dump the combined specular TOF information
    configure.dump_specular = options.dump_specular

    # set the ability to dump the combined background TOF information
    configure.dump_bkg = options.dump_bkg
    
    # set the ability to dump the combined normalization TOF information
    configure.dump_norm = options.dump_norm

    # set the ability to dump the combined normalization background TOF
    # information
    configure.dump_norm_bkg = options.dump_norm_bkg

    if options.dump_all:
        configure.dump_specular = True
        configure.dump_bkg = True        
        configure.dump_norm = True
        configure.dump_norm_bkg = True

    if options.timing:
        import sns_timing
        timer = sns_timing.DiffTime()
    else:
        timer = None

    # run the program
    run(configure, timer)
